-- =====================================================================
-- Store POS — MySQL schema (migration 001)
-- Ported from the project's original Supabase/Postgres design
-- (supabase/migrations/0001_schema.sql) to MySQL/InnoDB.
--
-- Design notes carried over from the original schema:
-- - IDs are CHAR(36) UUIDs, generated by the client or the API layer
--   (never AUTO_INCREMENT), so a sale created offline on a phone already
--   has its final ID before it ever reaches the server. This is what
--   makes idempotent sync possible (section 5/17 of the spec).
-- - Money columns are DECIMAL(12,2) — never FLOAT — to avoid rounding
--   drift on financial totals.
-- - Every store-owned table carries `store_id` so the API can enforce
--   tenant isolation in one place (see repositories/*.js: every query is
--   scoped by store_id, never trusts an ID alone).
-- =====================================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- ---------------------------------------------------------------------
-- stores
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stores (
  id          CHAR(36)      NOT NULL PRIMARY KEY,
  name        VARCHAR(200)  NOT NULL,
  address     VARCHAR(300),
  phone       VARCHAR(40),
  currency    VARCHAR(10)   NOT NULL DEFAULT 'MAD',
  tax_rate    DECIMAL(5,4)  NOT NULL DEFAULT 0.1000,
  created_at  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- users — Node.js owns authentication directly (no Supabase Auth).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id             CHAR(36)      NOT NULL PRIMARY KEY,
  store_id       CHAR(36)      NULL,
  name           VARCHAR(120)  NOT NULL,
  email          VARCHAR(190)  NOT NULL,
  password_hash  VARCHAR(255)  NOT NULL,
  role           ENUM('admin','manager','cashier') NOT NULL DEFAULT 'cashier',
  is_active      TINYINT(1)    NOT NULL DEFAULT 1,
  created_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_users_email (email),
  KEY idx_users_store (store_id),
  CONSTRAINT fk_users_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- categories
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
  id          CHAR(36)      NOT NULL PRIMARY KEY,
  store_id    CHAR(36)      NOT NULL,
  name        VARCHAR(100)  NOT NULL,
  created_at  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_categories_store_name (store_id, name),
  CONSTRAINT fk_categories_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- products
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
  id              CHAR(36)      NOT NULL PRIMARY KEY,
  store_id        CHAR(36)      NOT NULL,
  category        VARCHAR(100),
  name            VARCHAR(200)  NOT NULL,
  barcode         VARCHAR(64),
  sku             VARCHAR(64),
  price           DECIMAL(12,2) NOT NULL,
  cost            DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  tax_rate        DECIMAL(5,4)  NOT NULL DEFAULT 0.0000,
  stock_quantity  INT           NOT NULL DEFAULT 0,
  is_active       TINYINT(1)    NOT NULL DEFAULT 1,
  created_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_products_store (store_id),
  KEY idx_products_barcode (store_id, barcode),
  KEY idx_products_updated_at (store_id, updated_at),
  CONSTRAINT fk_products_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- sales — client_operation_id is the idempotency key from the Flutter
-- sync queue: a retried sync of the same offline sale must never create
-- a second row (section 5 & 17 of the spec).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sales (
  id                    CHAR(36)      NOT NULL PRIMARY KEY,
  store_id              CHAR(36)      NOT NULL,
  user_id               CHAR(36)      NOT NULL,
  client_operation_id   CHAR(36)      NOT NULL,
  subtotal              DECIMAL(12,2) NOT NULL,
  discount_total        DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  tax_total             DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total                 DECIMAL(12,2) NOT NULL,
  payment_status        ENUM('PENDING','PAID','PARTIALLY_PAID','REFUNDED') NOT NULL DEFAULT 'PAID',
  sale_status           ENUM('COMPLETED','CANCELLED','REFUNDED') NOT NULL DEFAULT 'COMPLETED',
  note                  VARCHAR(500),
  occurred_at           DATETIME      NOT NULL,
  created_at            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_sales_client_operation (store_id, client_operation_id),
  KEY idx_sales_store_created (store_id, created_at),
  KEY idx_sales_user (user_id),
  CONSTRAINT fk_sales_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
  CONSTRAINT fk_sales_user  FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- sale_items
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sale_items (
  id            CHAR(36)      NOT NULL PRIMARY KEY,
  sale_id       CHAR(36)      NOT NULL,
  product_id    CHAR(36)      NOT NULL,
  quantity      INT           NOT NULL,
  unit_price    DECIMAL(12,2) NOT NULL,
  subtotal      DECIMAL(12,2) NOT NULL,
  created_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_sale_items_sale (sale_id),
  KEY idx_sale_items_product (product_id),
  CONSTRAINT fk_sale_items_sale    FOREIGN KEY (sale_id)    REFERENCES sales(id)    ON DELETE CASCADE,
  CONSTRAINT fk_sale_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- payments — a sale can have more than one row (MIXED payment mode).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
  id                   CHAR(36)      NOT NULL PRIMARY KEY,
  sale_id              CHAR(36)      NOT NULL,
  user_id              CHAR(36)      NOT NULL,
  client_operation_id  CHAR(36)      NULL,
  amount               DECIMAL(12,2) NOT NULL,
  payment_method       ENUM('CASH','CARD','TRANSFER') NOT NULL,
  created_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_payments_sale (sale_id),
  UNIQUE KEY uq_payments_sale_operation (sale_id, client_operation_id),
  CONSTRAINT fk_payments_sale FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- expenses
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS expenses (
  id                   CHAR(36)      NOT NULL PRIMARY KEY,
  store_id             CHAR(36)      NOT NULL,
  user_id              CHAR(36)      NOT NULL,
  client_operation_id  CHAR(36)      NOT NULL,
  amount               DECIMAL(12,2) NOT NULL,
  category             VARCHAR(100)  NOT NULL,
  description          VARCHAR(500),
  occurred_at          DATETIME      NOT NULL,
  created_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_expenses_client_operation (store_id, client_operation_id),
  KEY idx_expenses_store_created (store_id, created_at),
  CONSTRAINT fk_expenses_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
  CONSTRAINT fk_expenses_user  FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- inventory_movements — append-only ledger; current stock is the running
-- sum, mirrored (denormalized) onto products.stock_quantity for fast reads.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_movements (
  id                   CHAR(36)      NOT NULL PRIMARY KEY,
  store_id             CHAR(36)      NOT NULL,
  product_id           CHAR(36)      NOT NULL,
  client_operation_id  CHAR(36)      NULL,
  quantity_delta       INT           NOT NULL,
  movement_type        ENUM('PURCHASE','SALE','RETURN','ADJUSTMENT','DAMAGE','TRANSFER') NOT NULL,
  reference_id         CHAR(36)      NULL,
  note                 VARCHAR(300),
  created_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_inventory_client_operation (store_id, client_operation_id),
  KEY idx_inventory_store_product (store_id, product_id),
  CONSTRAINT fk_inventory_store   FOREIGN KEY (store_id)   REFERENCES stores(id)   ON DELETE CASCADE,
  CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- sync_operations — server-side audit/log of every operation received
-- from a client's sync queue. This is what makes retries idempotent:
-- before applying an operation, syncService checks whether its
-- operation_id has already been recorded here.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sync_operations (
  id               CHAR(36)     NOT NULL PRIMARY KEY,
  operation_id     CHAR(36)     NOT NULL,
  store_id         CHAR(36)     NOT NULL,
  user_id          CHAR(36)     NULL,
  entity_type      VARCHAR(40)  NOT NULL,
  entity_id        CHAR(36)     NOT NULL,
  operation_type   ENUM('create','update','delete') NOT NULL,
  status           ENUM('applied','failed','duplicate') NOT NULL,
  error_message    VARCHAR(500),
  created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_sync_operation (store_id, operation_id),
  KEY idx_sync_store_created (store_id, created_at),
  CONSTRAINT fk_sync_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
